server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /exit-tax-calculator {
        try_files $uri $uri/ /exit-tax-calculator/index.html;
    }

    location = / {
        return 301 /exit-tax-calculator;
    }
}
